export const siteConfig = {
  businessName: 'José Hernández Tree Service',
  ownerName: 'José Hernández',
  phone: '(713) 291-6992',
  cleanPhone: '+17132916992',
  email: 'josehernandeztree@gmail.com',
  domain: 'https://hernandeztreeservice.com',
  primaryService: 'Tree Trimming',
  services: [
    'Tree Removal',
    'Landscaping Services',
    'Storm Damage Cleanup & Debris Hauling',
    'Stump Grinding',
    'Flower Bed Installation',
    'Mulching',
    'Lot Clearing',
  ],
  rating: 5.0,
  reviewCount: 50,
  yearsInBusiness: 25,
  serviceAreas: ['Humble', 'Dayton', 'Baytown', 'Spring', 'The Woodlands', 'Conroe'],
  allServiceAreas: [
    'Humble, TX', 'Dayton, TX', 'Baytown, TX', 'Spring, TX',
    'The Woodlands, TX', 'Conroe, TX', 'Atascocita, TX', 'Kingwood, TX',
    'Crosby, TX', 'Huffman, TX', 'Porter, TX', 'New Caney, TX',
  ],
  neighborhoods: 'Kingwood, Atascocita, Summerwood, Eagle Springs, Fall Creek, Lakeshore, Oakhurst, Walden, Lake Houston',
  testimonials: [
    { quote: 'José Hernández Tree Service did an amazing job trimming my tree. I highly recommend them for their detail and care.', name: 'Violetta Negrete', reviews: 1 },
    { quote: 'José Hernández Tree Service is very professional. I was quoted a great price, they were on time, and they did an awesome job. I would definitely hire them again in the future.', name: 'Joycelyn Rodriguez Sanes', reviews: 3 },
    { quote: 'They did an amazing job with my tree removal and stump grinding. The crew was on time, professional, and left everything super clean. Highly recommend.', name: 'Isury Watson', reviews: 1 },
    { quote: 'José Hernández Tree Service really did an extraordinary job for me. I can sincerely recommend them for their excellent work and professionalism.', name: 'Patricia Rodriguez', reviews: 1 },
    { quote: 'José Hernández Tree Service takes care of all our properties. Highly recommend their consistent quality.', name: 'Christopher Celona', reviews: 2 },
    { quote: 'So impressed with José Hernández Tree Service. I highly recommend them to anyone needing reliable tree work.', name: 'Maria Gonzalez', reviews: 2 },
  ],
  faqs: [
    { q: 'How much does a tree service estimate cost?', a: 'Nothing — every estimate from José Hernández Tree Service is 100% free with no strings attached. We come out, look at the job, and give you an honest, affordable price on the spot. No pressure, no obligation.' },
    { q: 'What areas do you serve?', a: 'We proudly serve Humble, Dayton, Baytown, Spring, The Woodlands, Conroe, and surrounding communities including Atascocita, Kingwood, Crosby, Huffman, Porter, New Caney, and everywhere in between.' },
    { q: 'Is José Hernández Tree Service insured?', a: 'Yes. We carry full liability insurance on every job. Your property, your home, and our crew are always covered. We are happy to provide proof of insurance upon request.' },
    { q: 'How fast can you remove a tree?', a: 'Most single-tree removals wrap up the same day. For bigger jobs or complex rigging situations, we will walk you through the timeline before we start. Emergency tree removal is available 24/7.' },
    { q: 'Do you offer stump grinding?', a: 'Absolutely. We grind stumps below grade level so the area is ready for sod, landscaping, flower beds, or whatever you have planned next.' },
    { q: 'Do you handle emergency tree removal after storms?', a: 'Yes — call us immediately at (713) 291-6992. Our crew is on standby around the clock for storm emergencies in the Humble, Spring, Baytown, and greater North Houston area. We will get to you as fast as safely possible.' },
    { q: 'What landscaping services do you offer?', a: 'Beyond tree work, we offer flower bed installation, mulching, lot clearing, and debris hauling. We are a full-service tree and landscape company serving homeowners and commercial properties at affordable prices.' },
  ],
};

export const serviceData = [
  {
    slug: 'tree-trimming',
    title: 'Tree Trimming & Pruning',
    image: '/tree_pro/hernandez_service_trimming.png',
    summary: 'Shape your trees, clear your roofline, and reduce storm risk with proper structural pruning from experienced climbers.',
    details: [
      'Crown thinning, raising, and deadwood removal',
      'Clearance cuts for roofs, driveways, and utility lines',
      'Cuts that keep the tree healthy and looking right',
    ],
    turnaround: 'Typically completed same visit',
    longDescription: 'Proper tree trimming is about more than aesthetics — it protects your home and keeps your trees healthy for decades. Our climbers perform crown thinning to reduce wind load, raise canopies for clearance over roofs and driveways, and remove deadwood that attracts pests and disease. We follow ISA pruning standards on every cut. The result: a safer, healthier, better-looking tree — all at a fair, affordable price.',
    keywords: ['tree trimming Humble TX', 'tree pruning Spring TX', 'crown thinning Baytown', 'tree shaping service Conroe'],
  },
  {
    slug: 'tree-removal',
    title: 'Tree Removal',
    image: '/tree_pro/hernandez_service_removal.png',
    summary: 'Dangerous, dead, or overgrown trees taken down safely — even in tight spots next to homes, fences, and power lines.',
    details: [
      'Rigging and sectional cuts for confined areas',
      'Full haul-off — we leave nothing behind',
      'Available 24/7 for storm emergencies',
    ],
    turnaround: 'Same day on most jobs',
    longDescription: 'Whether you have a dead oak threatening your roof, a leaning pine too close to the power lines, or a storm-damaged tree blocking your driveway, our crew handles it safely and efficiently. We use sectional rigging techniques to bring down trees piece by piece in tight spaces — protecting your home, fence, and landscaping. Every job includes full debris removal and haul-off. No mess left behind, guaranteed.',
    keywords: ['tree removal Humble TX', 'emergency tree removal Baytown', 'tree cutting service Spring TX', 'dead tree removal Conroe'],
  },
  {
    slug: 'landscaping',
    title: 'Landscaping Services',
    image: '/tree_pro/hernandez_service_flowerbed.png',
    summary: 'Full-service landscaping to transform your yard — from design and planting to cleanup and maintenance. Affordable options for every budget.',
    details: [
      'Yard design, planting, and seasonal cleanup',
      'Sod installation, edging, and bed work',
      'Affordable packages for residential and commercial',
    ],
    turnaround: 'Completed in 1–3 visits',
    longDescription: 'A well-maintained landscape transforms your curb appeal and property value instantly. We handle everything from yard design and planting to seasonal cleanup, sod installation, and ongoing maintenance. Whether you need a full front-yard makeover or regular upkeep, José Hernández Tree Service delivers professional results at prices that work for every budget.',
    keywords: ['landscaping Humble TX', 'landscaping service Spring TX', 'affordable landscaping Baytown', 'yard work Conroe TX'],
  },
  {
    slug: 'storm-cleanup',
    title: 'Storm Cleanup',
    image: '/tree_pro/hernandez_service_storm.png',
    summary: 'When a storm leaves your yard blocked or your home exposed, we mobilize fast to clear debris and make things safe.',
    details: [
      'Fallen trees and limbs removed from structures',
      'Driveways, walkways, and yards cleared',
      'All brush and debris hauled away',
    ],
    turnaround: 'Emergency dispatch available',
    longDescription: 'Texas storms do not wait — and neither do we. When a hurricane, tropical storm, or severe thunderstorm drops trees on your home, blocks your driveway, or leaves your yard looking like a war zone, our emergency crew mobilizes fast. We safely remove fallen trees from structures, clear debris from walkways and driveways, and haul everything away. Available 24/7, 365 days a year.',
    keywords: ['storm damage cleanup Humble TX', 'emergency tree service Baytown', 'hurricane tree removal Spring TX', 'storm debris removal Conroe'],
  },
  {
    slug: 'stump-grinding',
    title: 'Stump Grinding',
    image: '/tree_pro/hernandez_service_stump.png',
    summary: 'Old stumps ground below grade so you can reclaim the space — whether you want to plant, build, or just have a clean yard.',
    details: [
      'Ground 6–8 inches below surface',
      'Grindings cleaned up or spread on site',
      'Area left ready for sod or landscaping',
    ],
    turnaround: 'Most stumps done same day',
    longDescription: 'That old stump is not just an eyesore — it attracts termites, takes up usable yard space, and makes mowing a pain. Our commercial stump grinder removes stumps 6 to 8 inches below grade level, so you can lay sod, plant a garden, install a flower bed, or simply enjoy a clean, flat yard. We clean up all the grindings and leave the area ready for whatever comes next.',
    keywords: ['stump grinding Humble TX', 'stump removal Spring TX', 'tree stump grinder Baytown', 'stump grinding near me Conroe'],
  },
  {
    slug: 'mulching',
    title: 'Mulching',
    image: '/tree_pro/hernandez_service_mulch.png',
    summary: 'Fresh mulch spread across your beds, around trees, and along walkways. Keeps moisture in, weeds down, and makes your yard look maintained year-round.',
    details: [
      'Beds cleared and prepped before application',
      'Even spread at the right depth for your plants',
      'Variety of mulch types available',
    ],
    turnaround: 'Same-day for most properties',
    longDescription: 'Fresh mulch does triple duty — it suppresses weeds, retains soil moisture during Texas summers, and gives your entire landscape a clean, finished look. We clear out old mulch and debris, edge your beds, and apply a fresh layer at the right depth for your plants. We carry hardwood, cedar, cypress, and colored mulch options. Most residential properties are completed same-day at affordable rates.',
    keywords: ['mulching service Humble TX', 'mulch installation Spring TX', 'landscape mulching Baytown', 'mulch delivery Conroe'],
  },
];

export const navLinks = [
  { label: 'Home', href: '/' },
  { label: 'Services', href: '/services' },
  { label: 'About', href: '/about' },
  { label: 'Gallery', href: '/gallery' },
  { label: 'Reviews', href: '/#reviews' },
  { label: 'Blog', href: '/blog' },
  { label: 'Contact', href: '/contact' },
];
